export const Films = () => import('@/views/Films.vue')
export const Series = () => import('@/views/Series.vue')
export const Search = () => import('@/views/Search.vue')
export const FilmID = () => import('@/views/FilmID.vue')
export const SerieID = () => import('@/views/SerieID.vue')